services:
  datastore1:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config
          port1: 8080
          port2: 8090
    ports:
      - "8080:8080"  
      - "8090:8090"
  datastore2:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config2
          port1: 8081
          port2: 8091
    ports:
      - "8081:8081"  
      - "8091:8091" 
  datastore3:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config3
          port1: 8082
          port2: 8092
    ports:
      - "8082:8082"  
      - "8092:8092" 
  datastore4:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config4
          port1: 8083
          port2: 8093
    ports:
      - "8083:8083"  
      - "8093:8093" 
networks:
  default:
    name: datastore
    external: true